apiVersion : apps/v1
kind: Deployment
metadata:
  name: migosfinance 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migosfinance
  template:
    metadata:
      labels:
        app: migosfinance 
    spec:
      containers:
        - name: migosfinance 
          image: migos.azurecr.io/migosfinance
          ports:
          - containerPort: 3000