apiVersion : apps/v1
kind: Deployment
metadata:
  name: migosmonolith 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migosmonolith
  template:
    metadata:
      labels:
        app: migosmonolith 
    spec:
      containers:
        - name: migosmonolith 
          image: migos.azurecr.io/migosmonolith
          ports:
          - containerPort: 3000