apiVersion: apps/v1
kind: Deployment
metadata:
  name: migos
  namespace: migos-prod-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migos
  template:
    metadata:
      labels:
        app: migos
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: migos
          image: rgazonil/migos
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 512M
            limits:
              cpu: 1000m
              memory: 1024M
          env:
            # Name that we are going to access inside our container
            - name: PGUSER
              valueFrom:
                # Secret name on kube secret obj
                secretKeyRef:
                  name: pguser-secret
                  key: PGUSER
            - name: PGHOST
              valueFrom:
                # Secret name on kube secret obj
                secretKeyRef:
                  name: pghost-secret
                  key: PGHOST
            - name: PGPASSWORD
              valueFrom:
                # Secret name on kube secret obj
                secretKeyRef:
                  name: pgpassword-secret
                  key: PGPASSWORD
            - name: PGDATABASE
              valueFrom:
                # Secret name on kube secret obj
                secretKeyRef:
                  name: pgatabase-secret
                  key: PGDATABASE
            - name: PGPORT
              valueFrom:
                # Secret name on kube secret obj
                secretKeyRef:
                  name: pgport-secret
                  key: PGPORT