apiVersion: v1
kind: Service
metadata:
  name: migos
  namespace: default-1696776253192
spec:
  type: LoadBalancer
  selector:
    app: migos
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000