apiVersion: v1
kind: Service
metadata:
  name: migos
  namespace: default-1696776253192
spec:
  type: LoadBalancer
  selector:
    app: migos
  ports:
    - targetPort: 3000
      name: port3000
      port: 3000
      protocol: TCP
    - targetPort: 5432
      name: port5432
      port: 5432
      protocol: TCP