apiVersion: v1
kind: Service
metadata:
  name: migos-service
  namespace: migos-prod-namespace
spec:
  type: LoadBalancer
  ports:
    - targetPort: 3000
      name: port3000
      port: 3000
      protocol: TCP
  selector:
    app: migos
