apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
spec:
  ingressClassName: nginx
  rules:
    - host: migos.com
      http:
        paths:
          - path: /users
            pathType: ImplementationSpecific
            backend:
              service:
                name: migos-clusterip-srv
                port:
                  number: 3000