apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: migos.com
      http:
        paths:
          - path: /users
            backend:
              serviceName: migos-clusterip-srv
              servicePort: 3000