apiVersion: apps/v1
kind: Deployment
metadata:
  name: migos-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migos
  template:
    metadata:
      labels:
        app: migos
    spec:
      containers:
        - name: migos
          image: rgazonil/migos